// const navTitles = [
//   "Women Ethnic",
//   "Women Western",
//   "Jewellery & Accessories",
//   "Mens",
//   "Beauty & Wellness",
//   "Home & Kitchen",
//   "Bags & Footwear",
//   "Kids",
//   "Electronics",
// ];
const navTitles = [
  {
    title: "Women Ethnic",
    data: [
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
    ],
  },
  {
    title: "Women Western",
    data: [
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
    ],
  },
  {
    title: "Women Ethnic",
    data: [
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
    ],
  },
  {
    title: "Jewellery & Accessories",
    data: [
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
    ],
  },
  {
    title: "Mens",
    data: [
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
    ],
  },
  {
    title: "Beauty & Wellness",
    data: [
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
    ],
  },
  {
    title: "Home & Kitchen",
    data: [
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
    ],
  },
  {
    title: "Bags & Footwear",
    data: [
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
    ],
  },
  {
    title: "Electronics",
    data: [
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
      [
        "Sarees",
        "All Sarees",
        "Silk Sarees",
        "Banarasi Sarees",
        "Cotton Sarees",
        "Net Sarees",
      ],
    ],
  },
];
export default navTitles;
