const productsList = [
  {
    title: "Trendy Lalit Woven Design Cotton Saree",
    imgUrl: "/assets/productsfy/product-img.png",
    altText : "Woven Cotton Saree - IMG",
    currentPrice: "404",
    priceBeforeDisc: "434",
    discPercentage: "20",
    isFirstOrder: true,
    hasFreeDelivery: true,
    rating: 4.4,
    numRating: 534,
    isMTrusted: true,
  },
  {
    title: "Trendy Lalit Woven Design Cotton Saree",
    imgUrl: "/assets/productsfy/product-img.png",
    altText : "Woven Cotton Saree - IMG",
    currentPrice: "404",
    priceBeforeDisc: "434",
    discPercentage: "20",
    isFirstOrder: true,
    hasFreeDelivery: true,
    rating: 4.4,
    numRating: 534,
    isMTrusted: true,
  },
  {
    title: "Trendy Lalit Woven Design Cotton Saree",
    imgUrl: "/assets/productsfy/product-img.png",
    altText : "Woven Cotton Saree - IMG",
    currentPrice: "404",
    priceBeforeDisc: "434",
    discPercentage: "20",
    isFirstOrder: true,
    hasFreeDelivery: true,
    rating: 4.4,
    numRating: 534,
    isMTrusted: true,
  },
  {
    title: "Trendy Lalit Woven Design Cotton Saree",
    imgUrl: "/assets/productsfy/product-img.png",
    altText : "Woven Cotton Saree - IMG",
    currentPrice: "404",
    priceBeforeDisc: "434",
    discPercentage: "20",
    isFirstOrder: true,
    hasFreeDelivery: true,
    rating: 4.4,
    numRating: 534,
    isMTrusted: true,
  },
  {
    title: "Trendy Lalit Woven Design Cotton Saree",
    imgUrl: "/assets/productsfy/product-img.png",
    altText : "Woven Cotton Saree - IMG",
    currentPrice: "404",
    priceBeforeDisc: "434",
    discPercentage: "20",
    isFirstOrder: true,
    hasFreeDelivery: true,
    rating: 4.4,
    numRating: 534,
    isMTrusted: true,
  },
  {
    title: "Trendy Lalit Woven Design Cotton Saree",
    imgUrl: "/assets/productsfy/product-img.png",
    altText : "Woven Cotton Saree - IMG",
    currentPrice: "404",
    priceBeforeDisc: "434",
    discPercentage: "20",
    isFirstOrder: true,
    hasFreeDelivery: true,
    rating: 4.4,
    numRating: 534,
    isMTrusted: true,
  },
  {
    title: "Trendy Lalit Woven Design Cotton Saree",
    imgUrl: "/assets/productsfy/product-img.png",
    altText : "Woven Cotton Saree - IMG",
    currentPrice: "404",
    priceBeforeDisc: "434",
    discPercentage: "20",
    isFirstOrder: true,
    hasFreeDelivery: true,
    rating: 4.4,
    numRating: 534,
    isMTrusted: true,
  },
  {
    title: "Trendy Lalit Woven Design Cotton Saree",
    imgUrl: "/assets/productsfy/product-img.png",
    altText : "Woven Cotton Saree - IMG",
    currentPrice: "404",
    priceBeforeDisc: "434",
    discPercentage: "20",
    isFirstOrder: true,
    hasFreeDelivery: true,
    rating: 4.4,
    numRating: 534,
    isMTrusted: true,
  },
];
export default productsList;
